version: '3.9'

services:
  function-app:
    container_name: "function-app"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FUNCTIONS_WORKER_RUNTIME": python
      AzureWebJobsStorage: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
    restart: always
    ports:
      - "8080:80"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"